# Generated by Django 3.2.7 on 2021-10-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=200)),
                ('birthday', models.CharField(max_length=200)),
            ],
        ),
    ]
